# Generated by Django 3.2.4 on 2021-07-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Post Image'),
        ),
    ]
