# Generated by Django 3.2.4 on 2021-07-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20210707_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
