# Generated by Django 3.2.4 on 2021-07-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_auto_20210707_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
