# Generated by Django 3.2.5 on 2021-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product`s name')),
                ('description', models.TextField(help_text='Description text to describe the product', verbose_name='Description')),
                ('qty_in_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='Will this product be sold?')),
                ('type', models.CharField(choices=[('JPEG', 'Picture With Normal Quality'), ('PSD', 'Photoshop File'), ('AI', 'Illustrator File'), ('TEXT', 'A Word File'), ('PRINT', 'Print On Paper')], max_length=100)),
            ],
        ),
    ]
